function EN655001 = load_asc(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EN655001 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  EN655001 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  EN655001 = importfile("C:\Users\Pierre\Desktop\PostDoc_URI_Desktop\NES-LTER\LTER_MLD_Kd_CTD\en655\EN655_001.asc", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Apr-2021 18:00:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 47);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Scan", "TimeJ", "TimeS", "PrDM", "T090C", "T190C", "T2T190C", "C0Sm", "C1Sm", "C2C1Sm", "V0", "CStarAt0", "CStarTr0", "V1", "FlECOAFL", "V2", "AltM", "V3", "V4", "Sbeox0V", "V5", "Sbeox1V", "V6", "Par", "Cpar", "V7", "Spar", "Pumps", "Latitude", "Longitude", "DepSM", "Sal00", "Sal11", "Sigma00", "Sigma11", "Sbox0MmKg", "Sbox1MmKg", "OxsolMmKg", "OxsatMmKg", "Potemp090C", "Potemp190C", "SvCM", "SvCM1", "DzdtM", "Gpa", "Nbin", "Flag"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
EN655001 = readtable(filename, opts);

end